movies/urls.py
from django.urls import path
from . import views

app_name='movies'

urlpatterns = [
    path('',views.index,name='index'),
    path('<movie_id>',views.detail,name='detail')
    ]

nuakhaiApp/nuakhai/nuakhai/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('nuanews.urls')),
]

nuakhaiApp/nuakhai/nuanews/urls.py
from django.contrib import admin
from django.urls import path
from nuanews import views

urlpatterns = [
    path('', views.index, name='index'),
]

vidly/urls.py
from django.contrib import admin
from django.urls import path,include
from api.models import MovieResource
from . import views

movie_resource=MovieResource()
urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls)),
    
    #home page
    path('/',include())
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

# Create your models here.
class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name='movies'

movies/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
# models has a class Model
class Genre(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
class Movie(models.Model):
    title=models.CharField(max_length=255)
    release_year=models.IntegerField()
    number_in_stock=models.IntegerField()
    daily_rate=models.FloatField()
    #each movie needs to be associated with a genre(if a genre is deleted all the movies associated are deleted)
    genre=models.ForeignKey(Genre,on_delete=models.CASCADE)

    #adding a new field date_created
    date_created=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

nuakhaiApp/nuakhai/nuanews/models.py
from django.db import models

# Create your models here.

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404

#import Movie object from model
from .models import Movie

# Create your views here.
def index(request):
    #SELECT * FROM movies_movie WHERE release_year =1998; is equivalent to the following
    #Movie.object.filter(release_year=1998)

    #SELECT * FROM movies_movie WHERE id =1; is equivalent to the following
    #Movie.object.get(id=1)

    # SELECT * FROM movies_movie; is equivalent to the following API
    moviesObject = Movie.objects.all()
    allMovies='  and  '.join([m.title for m in moviesObject])

    #to render it in a template
    #pass the request and the name of the template file
    #create a dictionary and pass a key as movies and values as the moviesObject
    return render(request,'movies/index.html',{'movies':moviesObject})

    return HttpResponse(allMovies)
def detail(request,movie_id):
    # try:
        # movieDetailsObject=Movie.objects.get(id=movie_id)
        movieDetailsObject=get_object_or_404(Movie,id=movie_id)
        return render(request,'movies/details.html',{'movies_details':movieDetailsObject})
        #return HttpResponse(movie_id)

    # except Movie.DoesNotExist:
    #     raise Http404()
    

nuakhaiApp/nuakhai/nuanews/views.py
from django.shortcuts import render
from django.http import HttpResponse
from newsapi import NewsApiClient



# Create your views here.


def index(request):
    # return HtttpResponse('Welcome to NUA News')
    newsapi = NewsApiClient(api_key='7bfb27f9a56e4ad7adcda1eb46820a6e')
    # /v2/top-headlines
    top_headlines = newsapi.get_top_headlines(sources='techcrunch')
    l = top_headlines['articles']
    desc = []
    news = []
    img = []

    for i in range(len(l)):
        f = l[i]
        news.append(f['title'])
        desc.append(f['description'])
        img.append(f['urlToImage'])
    mylist = zip(news, desc, img)
    return render(request, 'index.html', context={'mylist': mylist})

vidly/views.py
from django.shortcuts import render

def home(request):
    return render(request,'home.html')

movies/templates/movies/details.html
{% extends 'base.html' %}
{% block content %}
<dl>
    <dt>Title</dt>
    <dd>{{movies_details.title}}</dd>
    <dt>Year</dt>
    <dd>{{movies_details.release_year}}</dd>
    <dt>Stock</dt>
    <dd>{{movies_details.number_in_stock}}</dd>
</dl>

{% endblock  %}

movies/templates/movies/index.html
{% extends "base.html" %}

{% block content  %}
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Title</th>
            <th>Genre</th>
            <th>Release Year</th>
        </tr>
    </thead>
    <tbody>
        {% for movie in movies %}
        <tr>
            <td>
                <!-- <a href="/movies/{{movie.id}}"> -->
                    <a href="{% url 'movies:detail' movie.id %}">
                    {{movie.title}}
                </a>
            </td>
            <td>{{movie.genre}}</td>
            <td>{{movie.release_year}}</td>
        </tr>
        {% endfor %}

    </tbody>
</table>
{% endblock  %}

nuakhaiApp/nuakhai/nuanews/templates/index.html
<!DOCTYPE html>
<html lang="en">

</html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <title>Nua NEWS</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <img src="scrollRL.jpg" alt=""><a class="navbar-brand" href="#"> ନୂଆଁଖାଇ</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <button type="button" class="btn btn-dark" style="margin-bottom: 2px;">ସମ୍ବଲପୁରୀ </button>
                    <button type="button" class="btn btn-primary" style="margin-bottom: 2px;">ରାଜନୀତି </button>
                    <button type="button" class="btn btn-secondary" style="margin-bottom: 2px;">ଓଲିଉଡ </button>
                    <button type="button" class="btn btn-success" style="margin-bottom: 2px;">ବିଦେଶଖବର </button>
                    <button type="button" class="btn btn-danger" style="margin-bottom: 2px;">ଗୀତ(Music)</button>
                    <button type="button" class="btn btn-warning" style="margin-bottom: 2px;">ଯାତ୍ରାଦୁନିଆ </button>
                    <button type="button" class="btn btn-info" style="margin-bottom: 2px;">କାରବାର(business)</button>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <div class="container">
        <h5>ପଶ୍ଚିମ ଓଡିଶା ର ଗଣପର୍ବ ନୂଆଁଖାଇ ଉପଲକ୍ଷେ ହାର୍ଦ୍ଧିକ ଅଭିନନ୍ଦନ!ନୂଆଁଖାଇ 2019ର କିଛି ଝଲକ </h5>
        <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="false">
            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                {%for new ,des,i in mylist%}
                {% if forloop.first %}
                <div class="active item">
                    {% else %}
                    <div class="item">
                        {% endif %}
                        <div style="margin-left: 10px;margin-right: 10px;margin-bottom: 20px;">
                            <h4>{{new}}</h4>
                            <img src="{{i}}" alt="" style="width:100%;">
                            <p>{{des}}</p>
                        </div>
                    </div>
                    {%endfor%}
                </div>
                <!-- Left and right controls -->
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <!-- bare minimum loop below -->
            <!-- {% comment %} {%for new ,des,i in mylist%}
        <img src="{{i}}" alt="">
        <h1>news:</h1>{{new}}
        <h4>description:</h4>{{des}}
        {{value|linebreaks}}
    {%endfor%} {% endcomment %} -->
        </div>
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>

</body>

</html>

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Vidly!</title>
</head>

<body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">Vidly</a>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock  %}
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>